require('core.plugin_config.lsp_config')
require('core.plugin_config.gruvbox')
-- require('core.plugin_config.rose_pine')
require('core.plugin_config.lualine')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.complitions')
require('core.plugin_config.luasnip')
require('core.plugin_config.comment')
require('core.plugin_config.which_key')
