#!/bin/bash

while :
do
    BLUETOOTH_DEVICES=$(bluetooth.sh)
    WIFI_CON=$(net.sh)
    VOL=$(volume.sh)
    BAT=$(battery.sh)
    TIME=$(date +%H:%M)
    xsetroot -name " $WIFI_CON|$BLUETOOTH_DEVICES$VOL | $BAT | $TIME " &> /dev/null
    # echo " $WIFI_CON|$BLUETOOTH_DEVICES$VOL | $BAT | $TIME " 
    sleep 1
done
