#!/bin/sh

# systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
# systemctl --user restart xdg-desktop-portal
systemctl --user start river-session.service & disown
swww restore &

riverctl map normal Super Return spawn footclient

riverctl map normal Super R spawn "/usr/local/bin/app-launcher "

riverctl map normal Super Q close

riverctl map normal Super+Control+Shift Q exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super Tab focus-previous-tags

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
# riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output -current-tags next
# riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Space zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super O send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift O send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# tags [0-9]
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# tags [11-20]
for i in $(seq 11 20)
do
    j=$(($i - 10))
    tags=$((1 << ($i - 1)))

    # to focus tag
    riverctl map normal Super "F$j" set-focused-tags $tags

    # to tag focused view with tag
    riverctl map normal Super+Shift "F$j" set-view-tags $tags

    # to toggle focus of tag
    riverctl map normal Super+Control "F$j" toggle-focused-tags $tags

    # to toggle tag of focused view
    riverctl map normal Super+Shift+Control "F$i" toggle-view-tags $tags
done

# tag 20
# riverctl map normal Super F19 set-focused-tags 20
# riverctl map normal Super+Shift F19 set-view-tags 20
# riverctl map normal Super+Control F19 toggle-focused-tags 20
# riverctl map normal Super+Shift+Control F19 toggle-view-tags 20

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
# riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
# riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'


    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map -repeat $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
                         
    riverctl map -repeat $mode Shift XF86AudioRaiseVolume  spawn '/usr/local/bin/audio-vol-up'
    riverctl map -repeat $mode Shift XF86AudioLowerVolume  spawn '/usr/local/bin/audio-vol-down'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode Control XF86AudioPlay  spawn '/usr/local/bin/audio-player-shift'

    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl keyboard-layout -options "grp:ctrl_space_toggle" "us,ru"
# riverctl keyboard-layout us,ru
# do not work
# riverctl map normal Control Space keyboard-layout next

riverctl map normal Super+Shift L spawn 'wlogout'
riverctl map normal Super+Shift V spawn 'pavucontrol'
riverctl map normal Super+Control T spawn 'Telegram'
riverctl map normal Super S spawn '/usr/local/bin/screenshot.sh'
riverctl map normal Super W  spawn 'firefox'


# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xf3a131
riverctl border-color-unfocused 0x586e75
riverctl border-width 3

# Set keyboard repeat rate
riverctl set-repeat 28 220

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "org.telegram.desktop" ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
# riverctl default-layout rivertile &
# riverctl default-attach-mode below &

# rivertile -view-padding 3 -outer-padding 6 &
# riverctl map normal Super A spawn '~/.config/river/toggle-padding.sh'

# set layout manager
riverctl default-layout wideriver

# start layout manager
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        diminish     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --smart-gaps                            \
    --inner-gaps                   5           \
    --outer-gaps                   8           \
    --border-width                 3           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      1           \
    --border-color-focused         "0xf3a131"  \
    --border-color-focused-monocle "0x586e75"  \
    --border-color-unfocused       "0x586e75"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &


riverctl map normal Super H send-layout-cmd wideriver "--ratio -0.025"
riverctl map normal Super L send-layout-cmd wideriver "--ratio +0.025"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super O send-layout-cmd wideriver "--count +1"
riverctl map normal Super+Shift O send-layout-cmd wideriver "--count -1"

riverctl map normal Super M send-layout-cmd wideriver "--layout monocle"
riverctl map normal Super D send-layout-cmd wideriver "--layout wide"

riverctl map normal Super T send-layout-cmd wideriver "--layout left --stack diminish"
riverctl map normal Super+Shift T send-layout-cmd wideriver "--layout left --stack even "
riverctl map normal Super Y send-layout-cmd wideriver "--layout left --stack dwindle"

riverctl map normal Super down send-layout-cmd wideriver "--layout bottom"
riverctl map normal Super up send-layout-cmd wideriver "--layout top"
riverctl map normal Super right send-layout-cmd wideriver "--layout right"
riverctl map normal Super left send-layout-cmd wideriver "--layout left"

