#!/bin/sh

xscreensaver -no-splash &> /dev/null &

hibernate() {
    st &
    # xscreensaver-command --lock
    # sleep 3
    i3lock -c 000000
    sleep 1
    systemctl hibernate
}

myshutdown() {
    systemctl poweroff -i
}

reboot() {
    systemctl reboot -i
    # shutdown --reboot now
}

suspend() {
    xscreensaver-command --lock
    sleep 3
    systemctl suspend
}

sleep_hibernate() {
    xscreensaver-command --lock
    sleep 3
    systemctl suspend-then-hibernate
}

screen_off() {
    xscreensaver-command --lock
    sleep 3
    xset dpms force off
}

lock() {
    xscreensaver-command --lock
}

"$@"
# load theme from pywal
. "${HOME}/.cache/wal/colors.sh"
DMEN="dmenu -nf $color15 -nb $color0 -sb $color5 -sf $color0"
select=$(echo -e "hibernate\nsleep\nzSleep-hibernate\nShutdown\nrestart\nlock\noff" | $DMEN -p power)
echo $select
case  $select in
    "hibernate") hibernate ;;
    "Shutdown") myshutdown ;;
    "sleep") suspend ;;
    "zSleep-hibernate") sleep_hibernate ;;
    "restart") reboot ;;
    "lock") lock ;;
    "off") screen_off;;
esac

