#!/bin/sh

xscreensaver -no-splash &> /dev/null &

run_via_nohup() {
    nohup $1 > /dev/null
}

hibernate() {
    run_via_nohup "systemctl hibernate"
}

myshutdown() {
    run_via_nohup "systemctl poweroff -i"
    screen_off
}

reboot() {
    run_via_nohup "systemctl reboot -i"
}

suspend() {
    run_via_nohup "systemctl suspend"
}

sleep_hibernate() {
    run "systemctl suspend-then-hibernate"
}

screen_off() {
    xset dpms force off
    killall dmenu
}

lock() {
    xscreensaver-command --lock
}

"$@"
# load theme from pywal
. "${HOME}/.cache/wal/colors.sh"
DMEN="dmenu -nf $color15 -nb $color0 -sb $color5 -sf $color0"
select=$(echo -e "Shutdown\nlock\nrestart\nhibernate\nsleep" | $DMEN -p power)
echo $select
case  $select in
    "hibernate") hibernate ;;
    "Shutdown") myshutdown ;;
    "sleep") suspend ;;
    "zSleep-hibernate") sleep_hibernate ;;
    "restart") reboot ;;
    "lock") lock ;;
    "off") screen_off;;
esac

killall dmenu
