#!/usr/bin/env sh
set -eu

eww_bin=/etc/profiles/per-user/mikhail/bin/eww
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/eww"

"$eww_bin" --config "$config_dir" active-windows | grep -q '^stats-popup-window:' && exit 0

exec "$eww_bin" --config "$config_dir" open stats-popup-window
