#!/usr/bin/env sh
set -eu

eww_bin=/etc/profiles/per-user/mikhail/bin/eww
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/eww"

"$eww_bin" --config "$config_dir" update media_popup_pinned=false || true
exec "$eww_bin" --config "$config_dir" close media-popup-window
