#!/usr/bin/env sh
set -eu

eww_bin=/etc/profiles/per-user/mikhail/bin/eww
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/eww"

exec "$eww_bin" --config "$config_dir" open --toggle calendar-popup-window
