#!/bin/bash

MON="eDP"    # Discover monitor name with: xrandr | grep " connected"

max_brightness=$(brightnessctl m)
current_brightness=$(brightnessctl get)

if [[ $current_brightness -lt $max_brightness ]] then
    brightnessctl  set +10% | grep -E -o '([0-9][0-9]%|1[0-9][0-9]%)'
    xrandr --output $MON --brightness 1.0
else
    xrandr --output $MON --brightness 1.3
fi
