#!/bin/bash

MON="eDP"    # Discover monitor name with: xrandr | grep " connected"

max_brightness=$(brightnessctl m)
current_brightness=$(brightnessctl get)

if [[ $current_brightness -lt $max_brightness ]] then
    brightnessctl  set +10% | grep -E -o '([0-9][0-9]%|1[0-9][0-9]%)'
    if [[ $current_brightness -lt 2 ]] then
        xrandr --output $MON --brightness 1.0
    fi
else
    if [[ $current_brightness -gt 254 ]] then
        xrandr --output $MON --brightness 1.3
    fi
fi
