#!/bin/bash

MON="eDP"    # Discover monitor name with: xrandr | grep " connected"

min_brightness=$(brightnessctl m)
current_brightness=$(brightnessctl get)

if [[ $current_brightness -ge $max_brightness ]] then
    brightnessctl  set 10%- | grep -E -o '([0-9][0-9]%|1[0-9][0-9]%)'
    xrandr --output $MON --brightness 1.0
else
    xrandr --output $MON --brightness 0.3
fi
