#!/bin/bash

if [[ "$(xinput list | grep Touchpad | awk '{print $5}')" == "Touchpad" ]]; then
    # echo "Touchpad found"
    tp_id=$(xinput list | grep Touchpad | awk '{print $6}' | awk -F"=" '{print $2}')
    echo "Touchpad enabled"
    logger "Touchpad enabled"
    xinput enable "$tp_id"
else
    echo "Touchpad not found"
    logger "Touchpad not found"
fi
