#!/bin/sh

[ $(pamixer --get-mute) = true ] && exit

threshold_volume=60
global_volume=$(pamixer --get-volume)

echo $threshold_volume
echo $global_volume

if [ $global_volume -ge $threshold_volume ]; then
    pamixer --set-volume $threshold_volume
    mpv --no-video ~/Music/composing/recordings/welcome.mp3 --no-resume-playback
    pamixer --set-volume $global_volume
# else 
    # mpv --no-video ~/Music/composing/recordings/welcome.mp3
fi
