#!/bin/bash

while :
do
    BLUETOOTH_DEVICES=$(bluetooth.sh)
    VPN=$(vpn.sh)
    NETWORK=$(net.sh)
    VOL=$(volume.sh)
    BAT=$(battery.sh)
    TIME=$(date +%H:%M)
    xsetroot -name " $VPN$NETWORK$BLUETOOTH_DEVICES$VOL | $BAT | $TIME " &> /dev/null
    sleep 1
done
