#!/bin/sh

current_kernel_governer=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
echo "current kernel governer = $current_kernel_governer"

powersave_str="powersave"

if [ "$current_kernel_governer" = "$powersave_str" ]; then
    echo "set frame rate to 60 fps"
    xrandr --rate 60
else
    echo "set frame rate to 144 fps"
    xrandr --rate 144
fi
