#!/bin/bash

if [[ "$(xinput list | grep Touchpad | awk '{print $5}')" == "Touchpad" ]]; then
    # echo "Touchpad found"
    tp_id=$(xinput list | grep Touchpad | awk '{print $6}' | awk -F"=" '{print $2}')
    if [[ "$(xinput list-props "$tp_id" | grep "Device Enabled" | awk '{print $4}')" == "1" ]]; then
        echo "Touchpad disabled"
        logger "Touchpad disabled"
        xinput disable "$tp_id"
        notify-send 'TouchPad disabled'
    else
        echo "Touchpad enabled"
        logger "Touchpad enabled"
        xinput enable "$tp_id"
        notify-send 'TouchPad enabled'
    fi
else
    echo "Touchpad not found"
    logger "Touchpad not found"
fi
